[package]
name = "ydns"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.8", features = ["derive"] }
reqwest = {version = "0.11.18", default-features = false, features = ["rustls-tls"] }
tokio = {version = "1.28.2", features = ["full"]}
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"